---
 - name: Metricbeat Install
   hosts: webservers
   become: yes
   tasks:

   - name: Download Metricbeat
     command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

   - name: Install Metricbeat
     command: dpkg -i metricbeat-7.6.1-amd64.deb

   - name: Drop in config
     copy:
      src: /etc/ansible/files/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml

   - name: Enable and configure
     command: metricbeat modules enable docker

   - name: Setup
     command: metricbeat setup

   - name: Start Service
     command: service metricbeat start

   - name: Enable on boot
     systemd:
      name: metricbeat
      enabled: yes
...
